# Generated by Django 3.0.3 on 2020-03-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='accounts.Profile')),
            ],
        ),
    ]
