# Generated by Django 3.0.3 on 2020-03-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expense', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='accounts.Profile')),
            ],
        ),
    ]
