# Generated by Django 3.0.3 on 2020-02-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done_by',
            field=models.ForeignKey(default='Jack', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='accounts.Profile'),
            preserve_default=False,
        ),
    ]
